/**
 * Brand artwork from public/art/ (3:2, 1200×800 JPG fallback + 800w/1600w AVIF/WebP).
 * Generated by `npm run art` from brand-source/art/*.png.
 *
 * Dark backgrounds: hero, dark-silk, dark-spiral.
 * Light backgrounds: official-labs, sandboxes, lab-machines, certifications,
 * training, ask-hexa, white-label, security, honeycomb.
 * Photography (ph-*): editorial photos for card media, photo stages, image bands and
 * inner-page heroes (ph-hero-* are low-key with dark space on the left for the headline).
 * Per-product (p-*): kept for reference only. Product cards show official logos
 * (LogoTile + src/content/products.ts).
 */
export const artNames = [
  'hero',
  'dark-silk',
  'dark-spiral',
  'official-labs',
  'sandboxes',
  'lab-machines',
  'certifications',
  'training',
  'ask-hexa',
  'white-label',
  'security',
  'honeycomb',
  // Photography
  'ph-cat-official',
  'ph-cat-sandboxes',
  'ph-cat-machines',
  'ph-cat-certifications',
  'ph-uc-batch',
  'ph-uc-sandbox',
  'ph-uc-windows',
  'ph-uc-kubernetes',
  'ph-uc-certifications',
  'ph-uc-whitelabel',
  'ph-band-datacenter',
  'ph-howitworks',
  'ph-steps-bg',
  'ph-trainer',
  'ph-support',
  'ph-security',
  'ph-cta',
  'ph-hero-official',
  'ph-hero-sandboxes',
  'ph-hero-labs',
  'ph-hero-certifications',
  'ph-hero-training',
  'ph-hero-pricing',
  'ph-hero-about',
  'ph-hero-contact',
  'ph-dd-console',
  'ph-dd-reports',
  'ph-about-team',
  'ph-wl-studio',
  // Use-case illustrations (square tiles cut from one 3×2 artwork, 2× upscaled)
  'il-uc-batch',
  'il-uc-oci',
  'il-uc-windows',
  'il-uc-kubernetes',
  'il-uc-vouchers',
  'il-uc-whitelabel',
  // White-label section illustration (shown whole, 3:2)
  'il-whitelabel',
  // Per-product artwork (unused on product cards — see LogoTile).
  'p-azure',
  'p-aws',
  'p-gcp',
  'p-oci',
  'p-databricks',
  'p-ai-foundry',
  'p-windows-server',
  'p-active-directory',
  'p-hyper-v',
  'p-ubuntu',
  'p-rhel',
  'p-oracle-db',
  'p-kubernetes',
  'p-openshift',
  'p-azure-openai',
  'p-jupyter',
  'p-devops',
] as const;

export type ArtName = (typeof artNames)[number];

/** Artwork with a dark background — use behind light text (heroes, dark bands). */
export const darkArt: readonly ArtName[] = ['hero', 'dark-silk', 'dark-spiral'];

type Props = {
  name: ArtName;
  /** Decorative by default. Give real alt text only when the image carries meaning. */
  alt?: string;
  /** Above-the-fold hero art: eager + high fetch priority. Everything else lazy-loads. */
  priority?: boolean;
  /** `sizes` attribute — how wide the image renders. */
  sizes?: string;
  /** Classes on the <picture> wrapper. */
  className?: string;
  /** Classes on the <img> (default: fills the wrapper with object-cover). */
  imgClassName?: string;
  /** CSS object-position for the photo's focal point, e.g. '50% 30%'. */
  position?: string;
};

export function Art({
  name,
  alt = '',
  priority = false,
  sizes = '(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw',
  className = '',
  imgClassName = 'h-full w-full object-cover',
  position,
}: Props) {
  const base = `/art/${name}`;
  // React 18 does not know the fetchPriority prop; the lowercase DOM attribute passes through.
  const priorityAttrs = priority ? ({ fetchpriority: 'high' } as Record<string, string>) : {};
  return (
    <picture className={`block ${className}`}>
      <source type="image/avif" srcSet={`${base}-800.avif 800w, ${base}-1600.avif 1600w`} sizes={sizes} />
      <source type="image/webp" srcSet={`${base}-800.webp 800w, ${base}-1600.webp 1600w`} sizes={sizes} />
      <img
        src={`${base}.jpg`}
        width={1200}
        height={800}
        alt={alt}
        loading={priority ? 'eager' : 'lazy'}
        decoding={priority ? 'auto' : 'async'}
        {...priorityAttrs}
        className={imgClassName}
        style={position ? { objectPosition: position } : undefined}
      />
    </picture>
  );
}
